@extends('control_panel.layouts')

@section('content')
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
@endsection