@extends('config.layouts')

@section('content')
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
    Hello <br>
@endsection